### PR TITLE
Add Child Protection Policy

### PR DESCRIPTION
**Pull request by wrussell1999**
Child Protection Policy based off the HackTheMidlands CPP, which I reviewed on the 21st October 2020 as Child Protection Officer.

Their policy can be found be found [here](https://hackthemidlands.com/docs/safeguarding/ChildProtectionPolicy.pdf).

Currently, I will be the Child Protection Officer / Designated Safeguarding Person for Hackathons for Schools Association. Once we've had some safeguarding training, others can  also become Designated Safeguarding Persons.

### CODE REVIEW

**Comment by wrussell1999** [comment]
Not sure why the Netlify preview isn't working. You should be able to read the document through the Markdown file.

**Review by danielfspencer — COMMENTED** [review]
Some bullet points start with capitals and some do not. We should choose one or the other.
(side note: I think there is no preview because you are not trying to merge into master)

**Comment by jac0bwilson** [comment]
I agree with Dan, needs to be a uniform style really. Also fixed a little typo with a file path, but not a big deal.

**Comment by wrussell1999** [comment]
That's fair. I'll go through and add them unless you want to

**Comment by wrussell1999** [comment]
I’ve added semicolons for most of the bullet points. I could also put these on the the longer paragraphs at the bottom. Bullet points look odd on small short bullet points, that’s all.

**Comment by wrussell1999** [comment]
If you want to swap it to all semicolons or full stops, feel free to edit the file :)

**Comment by jac0bwilson** [comment]
Looks good to me now, but you should take a look at the changes I just made and make sure its all still correct :)

**Comment by wrussell1999** [comment]
Looks good to me. Good catch with the formatting. I spent ages finding bits hiding but didn’t catch it all 😂

**Pull request merged**
